NautilusAccademia/GiocoFinale

Assets/Player_Animation_Prova/PG_low.controller, Assets/Script/Health.cs, Assets/Script/PlayerController3.cs
Ho cambiato i parametri delle animazioni passo e chiudo
=> Animazione: Idle,Walk(Bool),Taken(Trigger),Death(Trigger)

Assets/Scenes/Element.unity
Sistemato bug dove il giocatore non poteva prenderlo piu' di una volta
=> Portale sistemato

Assets/Modelli Presente/1.3.meta, Assets/Modelli Presente/1.3/PARTE_FINALE_TUBO_FERRO.obj, Assets/Modelli Presente/1.3/PARTE_FINALE_TUBO_FERRO.obj.meta, Assets/Modelli Presente/1.3/Piattaforma_media.obj, Assets/Modelli Presente/1.3/Piattaforma_media.obj.meta, Assets/Modelli Presente/1.3/Piattaforma_media_piccola_1x1x1_.fbx, Assets/Modelli Presente/1.3/Piattaforma_media_piccola_1x1x1_.fbx.meta, Assets/Modelli Presente/1.3/Piattaforma_piccola.obj, Assets/Modelli Presente/1.3/Piattaforma_piccola.obj.meta, Assets/Modelli Presente/1.3/Porta_Pietra.obj, Assets/Modelli Presente/1.3/Porta_Pietra.obj.meta, Assets/Modelli Presente/1.3/Suolo_4_4_1.fbx, Assets/Modelli Presente/1.3/Suolo_4_4_1.fbx.meta, Assets/Modelli Presente/1.3/bottone_piccolo.obj, Assets/Modelli Presente/1.3/bottone_piccolo.obj.meta, Assets/Modello Passato/1.3.meta, Assets/Modello Passato/1.3/piattaforma_media_piccola_1x1x1.fbx, Assets/Modello Passato/1.3/piattaforma_media_piccola_1x1x1.fbx.meta, Assets/Modello Passato/1.3/suolodistrutto.fbx, Assets/Modello Passato/1.3/suolodistrutto.fbx.meta, Assets/Prefab/Environment/1.3.meta, Assets/Prefab/Particles.meta, Assets/Prefab/Particles/Air.prefab, Assets/Prefab/Particles/Air.prefab.meta, Assets/Scenes/Livello_1.3.unity
Creato la base per il livello 1.3 e ho posizionato gli oggetti in scena e il prefab del particellare dell'aria.
=> Arredamento 1.3

Assets/Prefab/Environment/1.3.meta, Assets/Prefab/HUD/Canvas.prefab, Assets/Scenes/Element.unity, Assets/Scenes/MenùStart.unity, Assets/Scenes/MenùStart.unity.meta, Assets/Script/PauseMenu1.cs, ProjectSettings/EditorBuildSettings.asset
Creato Scena e canvas del Menù di Start;
Aggiunto il bottone e lo script per accedere al menù di start dal menù di pausa;
=> Menù di Start

Assets/Scenes/Element.unity, Assets/Scenes/MenùStart.unity, Assets/Script/SaveSystem.meta, Assets/Script/SaveSystem/ContinueButton.cs, Assets/Script/SaveSystem/ContinueButton.cs.meta, Assets/Script/SaveSystem/StartButton.cs, Assets/Script/SaveSystem/StartButton.cs.meta, Assets/Script/SaveSystem/ToMenu.cs, Assets/Script/SaveSystem/ToMenu.cs.meta, Assets/Script/SaveSystem/ToNextScene.cs, Assets/Script/SaveSystem/ToNextScene.cs.meta
Passaggio tra le varie scene e salvataggio della scena in cui si trova il player.
SCRIPT- StartButton, ToMenu, ToNextScene,ContinueButton,MainMenu
=> Save_System

Assets/Materials/Acqua_Prova.mat, Assets/Materials/Acqua_Prova.mat.meta, Assets/Materials/Ghiaccio_Prova.mat, Assets/Materials/Ghiaccio_Prova.mat.meta, Assets/Modelli Presente/1.4.meta, Assets/Modelli Presente/1.4/Valvola di ferro.obj, Assets/Modelli Presente/1.4/Valvola di ferro.obj.meta, Assets/Modelli Presente/1.4/tubointermedio.obj, Assets/Modelli Presente/1.4/tubointermedio.obj.meta, Assets/Modelli Presente/1.4/tubointero.obj, Assets/Modelli Presente/1.4/tubointero.obj.meta, Assets/Modelli Presente/1.4/tubopartefinale.obj, Assets/Modelli Presente/1.4/tubopartefinale.obj.meta, Assets/Scenes/Livello_1.4.unity, Assets/Scenes/Livello_1.4.unity.meta
Non è bellismo, ma è un  lavoro onesto.
=> Livello 1.4 arredato con i segnaposto

Assets/Materials/PlayerMaterial.mat, Assets/Materials/PlayerMaterial.mat.meta, Assets/Materials/lambert1 - Copia.mat, Assets/Materials/lambert1 - Copia.mat.meta, Assets/Materials/lambert1.mat, Assets/Materials/lambert1.mat.meta, Assets/Materials/mantella_01_defaultMat1 - Copia.mat, Assets/Materials/mantella_01_defaultMat1 - Copia.mat.meta, Assets/Materials/mantella_01_defaultMat1.mat, Assets/Materials/mantella_01_defaultMat1.mat.meta, Assets/Player_Animation_Prova/Player_Walk.fbx.meta, Assets/Scenes/Livello_1.2.unity, Assets/Script/Damage.cs, Assets/Script/Health.cs, Assets/Script/PlayerController3.cs
La trappola spinge via il giocatore quando si attiva, il giocatore perde vita e puoi muore pure (evviva).
=> Mo' la trappola funziona

Assets/Prefab/Environment/1.3.meta, Assets/RenderPipeline.meta, Assets/Scenes/Livello_1.3.unity, Assets/Scenes/Livello_1.4.unity
Ci sono i collider ai bordi del pavimento
=> Ho messo i collider

Assets/Prefab/Particles/Water/WaterParticles 1.png, Assets/Prefab/Particles/Water/WaterParticles 4.png, Assets/Prefab/Particles/Water/WaterParticles 4.png.meta, Assets/Prefab/Particles/Water/WaterParticles 5.png, Assets/Prefab/Particles/Water/WaterParticles 5.png.meta, Assets/Prefab/Particles/Water/WaterParticles.prefab, Assets/Prefab/Particles/Water/WaterParticles.prefab.meta, Assets/Prefab/Particles/Water/WaterSubParticles 1.mat, Assets/Prefab/Particles/Water/WaterSubParticles 1.mat.meta, Assets/Prefab/Particles/Water/WaterSubParticles 1.png, Assets/Prefab/Particles/Water/WaterSubParticles 1.png.meta, Assets/Prefab/Particles/Water/WaterSubParticles 2.png, Assets/Prefab/Particles/Water/WaterSubParticles 2.png.meta, Assets/Scenes/Livello_1.3.unity
Aggiunte le modifiche richieste per il particellare dell'acqua (interagibile)
=> Particellare Acqua

Assets/Particellari_Assets/Prefabs/LittleFireInHand.prefab, Assets/Prove_Elisa/Camera.cs, Assets/Scenes/Element.unity, Assets/Script/Player/Giulio_Barresi/CameraPan.cs, Assets/Script/Player/Giulio_Barresi/FireOnBrazier.cs, Assets/Script/PlayerController3.cs
Sistemato il fuocherello del player sulla testa non fa piu' la scia
e altre cose di cui non ricordo ciao.
=> Fuocherello del player

Assets/Script/Player/Giulio_Barresi/CameraPan.cs
Adesso il player non si muove se avviene un pan
=> Input ignorato al pan

Assets/Prefab/Trappola_Spuntoni_UV.prefab, Assets/Prove_Elisa/TrapDamage2.cs, Assets/Prove_Elisa/TrapDamage2.cs.meta, Assets/Prove_Elisa/Trappola_Spuntoni_uv_lUCI_polySurface3.controller, Assets/Prove_Elisa/idle_spuntoni.anim, Assets/Prove_Elisa/idle_spuntoni.anim.meta, Assets/Prove_Elisa/spuntoni_fuori.anim, Assets/Prove_Elisa/spuntoni_fuori.anim.meta, Assets/Scenes/Livello_1.2.unity, Assets/Script/Health.cs, Assets/Script/PlayerController3.cs
Trappole sistemate da Elisa
Ho solo fatto in modo di poter uppare
=> modifiche varie

Assets/Player_Animation_Prova/PG_low.controller
Sistemata uscita animazione take ora non blocca l'animazione camminata, tutto fluido
=> Animation_Take

Assets/Materiali/FireColor.mat, Assets/Modello Passato/1.2/pulsante.mat, Assets/Prefab/CRYSTAL.prefab, Assets/Prefab/CRYSTAL.prefab.meta, Assets/Prefab/collezionabileinutile.prefab, Assets/Prefab/collezionabileinutile.prefab.meta, Assets/Prove_Elisa/CRYSTAL.fbx, Assets/Prove_Elisa/CRYSTAL.fbx.meta, Assets/Scenes/Livello_1.2.unity, Assets/Script/FalsePickup.cs, Assets/Script/FalsePickup.cs.meta
=> Sistemazione trappole

Assets/Prefab/HUD/Canvas.prefab, Assets/Scenes/GameOver.unity, Assets/Scenes/Livello_1.2.unity, Assets/Scenes/Livello_1.3.unity, Assets/Script/PauseMenu1.cs, Assets/Script/SaveSystem/ToMenu.cs
Sono stati risolti i problemi inerenti i menù:
Il menù di pausa funziona correttamente in tutte le scene presenti e il menu di game over permettere di chiudere il gioco.
=> Sistemazione Menu

Assets/Script/PauseMenu1.cs
Modificato il pulsante che attiva il menu di pausa. Invece di essere la barra spaziatrice, adesso sono sia P che Esc.
=> Menu di pausa

Assets/Prefab/Particles/Earth/EarthParticles1.prefab, Assets/Prefab/Particles/Earth/EarthSubParticles1.3.mat, Assets/Prefab/Particles/Earth/EarthSubParticles1.3.mat.meta, Assets/Prefab/Particles/Earth/EarthSubParticles1.4.mat, Assets/Prefab/Particles/Earth/EarthSubParticles1.4.mat.meta, Assets/Prefab/Particles/Earth/masso1Particles.fbx, Assets/Prefab/Particles/Earth/masso1Particles.fbx.meta, Assets/Prefab/Particles/Earth/masso2Particles.fbx, Assets/Prefab/Particles/Earth/masso2Particles.fbx.meta, Assets/Scenes/Livello_1.3.unity
Modificato il particellare della terra
=> Particellari

Assets/Scenes/Element.unity, Assets/Scenes/Livello_1.2.unity, Assets/Scenes/Livello_1.3.unity
I bottoni del menu di pausa adesso funzionano se cliccati
=> Risoluzione Bottoni menu pausa

Assets/Prefab/Particles/Earth/EarthParticles1.prefab
Apportate le modifiche richieste al particellare di terra
=> Particellare terra

Assets/Prefab/Particles/Water/WaterParticles_Tubi.prefab
Apportate le modifiche richieste al particellare dell'acqua che esce dai tubi
=> Acqua tubi

Assets/Prefab/Particles/Air/Air Particles 2.png, Assets/Prefab/Particles/Air/Air Particles 3.png, Assets/Prefab/Particles/Air/Air Particles 5.png, Assets/Prefab/Particles/Air/Air Particles 5.png.meta, Assets/Prefab/Particles/Air/Air Particles 6.png, Assets/Prefab/Particles/Air/Air Particles 6.png.meta, Assets/Prefab/Particles/Air/Air Particles.png, Assets/Prefab/Particles/Air/AirParticlesShoot.mat, Assets/Prefab/Particles/Air/AirParticlesShoot.mat.meta, Assets/Prefab/Particles/Air/AirShoot.prefab, Assets/Prefab/Particles/Air/AirShootInHand.prefab, Assets/Prefab/Particles/Air/AirWall.prefab, Assets/Prefab/Particles/Water/WaterParticles_TubiXscript.prefab, Assets/Scenes/Livello_1.3.unity
Modificato il particellare d'aria, sia di raccolta che di sparo, e le modifiche richieste al colore del particellare dell'acqua che esce dai tubi sono state applicate
=> Modifiche Particellari

Assets/Prefab/Particles/Gas.meta, Assets/Prefab/Particles/Gas/Gas Particles 1.png, Assets/Prefab/Particles/Gas/Gas Particles 1.png.meta, Assets/Prefab/Particles/Gas/Gas1.prefab, Assets/Prefab/Particles/Gas/Gas1.prefab.meta, Assets/Prefab/Particles/Gas/GasParticles1.mat, Assets/Prefab/Particles/Gas/GasParticles1.mat.meta
Creata una bozza per il particellare del gas velenoso
=> Particellare Gas Velenoso

Assets/Prefab/Particles/Gas/Gas1.prefab, Assets/Prefab/Particles/Gas/Gas2.prefab, Assets/Prefab/Particles/Gas/Gas3.prefab, Assets/Prefab/Particles/Gas/Gas4.prefab
L'alpha delle proposte del particellare del gas è stato diminiuto
=> Particellari Gas

Assets/Prefab/Environment/Braciere_Basso_Rotto.meta, Assets/Prefab/HUD/e_giusta.png, Assets/Prefab/HUD/e_giusta.png.meta, Assets/Scenes/Element.unity
Sistemata la posizione del fuoco  e la è nel font voluto dai piani alti
=> Fuoco_IntE

Assets/Modello Passato/1.1/Vaso_Pianta/Materials/TwoSidedShader.shader, Assets/Modello Passato/1.1/Vaso_Pianta/Materials/TwoSidedShader.shader.meta, Assets/Modello Passato/1.1/Vaso_Pianta/Materials/vaso_sano_texture (1).mat
Adesso i fiori del vaso hanno due facce
=> Doppie facce
